Feature/save as
ONLYOFFICE/onlyoffice-confluence pull request #49
Opened 2021-09-02 08:14 UTC by aleksandrfedorov97

Added "save as" attachment on page from editor

2021-09-02 08:45 UTC, Eloncase approved these changes

2021-09-03 06:44 UTC, LinneyS requested changes

2021-09-03 06:44 UTC, LinneyS commented on src/main/resources/templates/editor.vm
> +                if (check) {
`errors` ?

2021-09-03 06:44 UTC, LinneyS commented on src/main/java/onlyoffice/OnlyOfficeSaveFileServlet.java
> +                    create(request, response);
Move to separate servlet

2021-09-03 08:46 UTC, merged